### ISSUE TITLE
CI, TST: too many figures opened

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan-logs#34]
See gh-33 for details, I think some of the HDF5 additions may reveal additional issues with too many `matplotlib` figures being left open.

` RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).`

**Comment by nawtrey** [comment]
I actually ran into this yesterday locally, but I just restarted my terminal and it never showed up again. At the moment it shows up if I run `pytest --import-mode=importlib` (as opposed to `pytest --pyargs darshan`), so I'll see if I can't fix this

**Comment by tylerjereddy** [comment]
Should be fixed by cross-listed PR in main repo.
