### ISSUE TITLE
MAINT: restore darshan-apmpi-2nodes-64mpi.darshan

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan-logs#6]
https://github.com/darshan-hpc/darshan-logs/pull/5 aims to remove an html file masquerading as a darshan log file with the name in the title above--I suggest that we try to add the log file proper at some point and this issue is simply a placeholder for that action.

**Comment by carns** [comment]
Hi @sudheer9 do you have the original log that was supposed to be here (added in https://github.com/darshan-hpc/darshan-logs/pull/1) ?

If not, we need to revert that PR.  I should have looked more carefully at the PR, but the *.darshan file is actually an HTML document of some sort.

**Comment by sudheer9** [comment]
@carns sorry, I too did not realize that.

**Comment by carns** [comment]
Thanks @sudheer9 , I just committed the updated log you provided.
